/*-----------------------------------------------------------------------------
    Name: next
    Generated By: cavisson
    Date of generation: 08/24/2021 10:51:29
    Flow details:
    Build details: 4.6.1 (build# 55)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void next()
{
	ns_start_transaction("next_page");
    ns_browser("next_page",
        "url=https://www.lowes.com/l/lowes-home-services.html",
        "browserurl=https://www.lowes.com/l/lowes-home-services.html",
        "action=Home",
        "title=Lowe's Home Improvement",
        "Snapshots=webpage_1629781873357.png");
    ns_end_transaction("next_page", NS_AUTO_STATUS);

    ns_page_think_time(16.57);
}