/*-----------------------------------------------------------------------------
    Name: Doodles
    Generated By: cavisson
    Date of generation: 08/20/2021 10:32:59
    Flow details:
    Build details: 4.6.1 (build# 55)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void Doodles()
{
	ns_start_transaction("Doodles_LightHouse");
    ns_browser("Doodles_LightHouse",
        "url=https://www.google.com/doodles",
        "browserurl=https://www.google.com",
        "action=Home",
        "title=Google",
        "Snapshots=webpage_1629433330526.png");
    ns_end_transaction("Doodles_LightHouse", NS_AUTO_STATUS);

    ns_page_think_time(7.44);
}