/*-----------------------------------------------------------------------------
    Name: HomePage
    Generated By: cavisson
    Date of generation: 08/20/2021 10:24:27
    Flow details:
    Build details: 4.6.1 (build# 55)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void HomePage()
{

    ns_start_transaction("HomePage_LightHouse");
    ns_browser("HomePage_LightHouse",
        "url=https://www.google.com/",
        "browserurl=https://www.google.com",
        "action=Home",
        "title=Google",
        "Snapshots=webpage_1629433289224.png");
    ns_end_transaction("HomePage_LightHouse", NS_AUTO_STATUS);

    ns_page_think_time(7.44);
}